version: '3.9'


services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: web
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306